# ~/.config/starship.toml


# è¾“å‡ºåæ¢è¡Œ
add_newline = true


# ç”µæ± å›¾æ ‡
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "


# å½“ç”µé‡åœ¨ 0% åˆ° 10% æ—¶ä»¥ "bold red" æ ·å¼æ˜¾ç¤º
[[battery.display]]
threshold = 30
style = "bold red"


# å½“ç”µé‡åœ¨ 10% åˆ° 30% æ—¶ä»¥ "bold yellow" æ ·å¼æ˜¾ç¤º
[[battery.display]]
threshold = 60
style = "bold yellow"


# å½“ç”µé‡åœ¨ 10% åˆ° 30% æ—¶ä»¥ "bold blue" æ ·å¼æ˜¾ç¤º
[[battery.display]]
threshold = 100
style = "bold blue"


# æ˜¾ç¤ºæ—¶é—´
[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "+8"
time_range = "10:00:00-14:00:00"


# åå°ä»»åŠ¡
[jobs]
symbol = "+ "
threshold = 4


# Git åˆ†æ”¯å›¾æ ‡
[git_branch]
symbol = "ğŸ”± "